# List all the .tex files here
TEXFILES = Catalan_Numbers.tex Counting.tex Functions_between_sets.tex \
           Generating_functions.tex Inclusion_Exclusion.tex \
           Partitions_StirlingNumbers.tex Permutations_Derangements.tex \
           lectures01.tex

# Define the corresponding PDF files
PDFS = $(TEXFILES:.tex=.pdf)

# Default target: build all PDFs
all: $(PDFS)

# Rule to build a PDF from a .tex file using latexmk
%.pdf: %.tex
	latexmk -pdf $<

# Clean up auxiliary files generated by latexmk
clean:
	latexmk -C

.PHONY: all clean
